name: 'Pull Request'

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      infrastructure-root: ${{ steps.diff.outputs.infrastructure-root }}
      infrastructure-prod: ${{ steps.diff.outputs.infrastructure-prod }}
      infrastructure-dev: ${{ steps.diff.outputs.infrastructure-dev }}
    steps:
      - uses: actions/checkout@v5
      - id: diff
        uses: ./.github/actions/github-file-diff

  infrastructure-root:
    needs: diff
    if: needs.diff.outputs.infrastructure-root == 'true' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - id: secrets
        uses: ./.github/actions/gcp-secret-manager
        with:
          project_id: 'web-app-demo-root'
          workload_identity_provider: 'projects/web-app-demo-root/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@web-app-demo-root.iam.gserviceaccount.com'
          secrets_list: |
            TF_VAR_github_provider_token=github_provider_token
      - uses: ./.github/actions/terraform-pull-request
        with:
          terraform_directory: 'infrastructure/root'
          config_directory: 'infrastructure/config/root'
          secrets: ${{ steps.secrets.outputs.secrets }}

  infrastructure-prod:
    needs: diff
    if: needs.diff.outputs.infrastructure-prod == 'true' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/terraform-pull-request
        with:
          terraform_directory: 'infrastructure/env'
          config_directory: 'infrastructure/config/prod'

  infrastructure-dev:
    needs: diff
    if: needs.diff.outputs.infrastructure-dev == 'true' && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/terraform-pull-request
        with:
          terraform_directory: 'infrastructure/env'
          config_directory: 'infrastructure/config/dev'
