name: 'Pull Request'

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      infrastructure-root: ${{ steps.diff.outputs.infrastructure-root }}
      infrastructure-prod: ${{ steps.diff.outputs.infrastructure-prod }}
      infrastructure-dev: ${{ steps.diff.outputs.infrastructure-dev }}
      service-backend: ${{ steps.diff.outputs.service-backend }}
    steps:
      - uses: actions/checkout@v5
      - id: diff
        uses: ./.github/actions/github-file-diff

  infrastructure-root:
    needs: diff
    if: needs.diff.outputs.infrastructure-root == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - id: secrets
        uses: ./.github/actions/gcp-secret-manager
        with:
          project_id: ${{ vars.ROOT_PROJECT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          secrets_list: |
            TF_VAR_github_provider_token=github_provider_token
      - uses: ./.github/actions/terraform-pull-request
        with:
          terraform_directory: 'infrastructure/root'
          config_directory: 'infrastructure/config/root'
          environment_name: 'root'
          secrets: ${{ steps.secrets.outputs.secrets }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  infrastructure-prod:
    needs: diff
    if: needs.diff.outputs.infrastructure-prod == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - id: secrets
        uses: ./.github/actions/gcp-secret-manager
        with:
          project_id: 'web-app-demo-prod'
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          secrets_list: ""
      - uses: ./.github/actions/terraform-pull-request
        with:
          terraform_directory: 'infrastructure/env'
          config_directory: 'infrastructure/config/prod'
          environment_name: 'prod'
          secrets: ${{ steps.secrets.outputs.secrets }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  infrastructure-dev:
    needs: diff
    if: needs.diff.outputs.infrastructure-dev == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - id: secrets
        uses: ./.github/actions/gcp-secret-manager
        with:
          project_id: 'web-app-demo-dev'
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          secrets_list: ""
      - uses: ./.github/actions/terraform-pull-request
        with:
          terraform_directory: 'infrastructure/env'
          config_directory: 'infrastructure/config/dev'
          environment_name: 'dev'
          secrets: ${{ steps.secrets.outputs.secrets }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  backend:
    needs: diff
    if: needs.diff.outputs.service-backend == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/backend-pull-request
